services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    network_mode: host # 共享宿主机网络，访问frp暴露的9900和9901端口
    restart: unless-stopped
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro

